#ifndef ANSI_H
#define ANSI_H

#define ANSI_PREFIX	"\e["
#define ANSI_SUFFIX	"m"

#define ANSI_RESET	"0"
#define ANSI_BOLD	"1;"
#define ANSI_UNDERLINE	"4;"

#define ANSI_FG_BLACK	"30"
#define ANSI_FG_RED	"31"
#define ANSI_FG_GREEN	"32"
#define ANSI_FG_YELLOW	"33"
#define ANSI_FG_BLUE	"34"
#define ANSI_FG_MAGENTA	"35"
#define ANSI_FG_CYAN	"36"
#define ANSI_FG_WHITE	"37"

#define ANSI_BG_BLACK	"40"
#define ANSI_BG_RED	"41"
#define ANSI_BG_GREEN	"42"
#define ANSI_BG_YELLOW	"43"
#define ANSI_BG_BLUE	"44"
#define ANSI_BG_MAGENTA	"45"
#define ANSI_BG_CYAN	"46"
#define ANSI_BG_WHITE	"47"

#define ANSI(CODE)			ANSI_PREFIX CODE ANSI_SUFFIX
#define ANSI_BOLD_FN(CODE)		ANSI_PREFIX ANSI_BOLD CODE ANSI_SUFFIX
#define ANSI_UNDERLINE_FN(CODE)		ANSI_PREFIX ANSI_UNDERLINE CODE ANSI_SUFFIX
#define ANSI_BOLD_UNDERLINE_FN(CODE)	ANSI_PREFIX ANSI_BOLD ANSI_UNDERLINE CODE ANSI_SUFFIX
#define ANSI_FG_RGB(R, G, B)		ANSI_PREFIX "38;2;" R ";" G ";" B ANSI_SUFFIX
#define ANSI_BG_RGB(R, G, B)		ANSI_PREFIX "48;2;" R ";" G ";" B ANSI_SUFFIX

#endif // ANSI
